# -*- mode: ruby -*-
# vi: set ft=ruby :

slu_box_name =  "macos-15.3.2"
vm_name_default = "test-macos-setup"
vm_name_file = ".vagrant_vm_name"

## Use contents of vm_name_file if it exists, otherwise use vm_name_default
vm_name = File.file?(vm_name_file) ? IO.read(vm_name_file).strip : vm_name_default

Vagrant.configure("2") do |config|
  config.vm.box = "slu/" + slu_box_name
  config.vm.box_url = "https://filedn.com/l5sQTlB8iglSMQibt69Jdj8/boxes/slu-" + slu_box_name + ".json"
  config.vm.box_check_update = false
  config.vm.hostname = vm_name
  config.vm.define vm_name

  config.vm.provider "parallels" do |prl|
    prl.name = vm_name
    prl.update_guest_tools = false
  end

end


