---
- name: Set up macOS for actual work
  hosts: all
  vars_files:
    - packages.yml
    - dotfiles.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/software.yml
    - ansible.builtin.include_tasks: tasks/dotfiles.yml
    - ansible.builtin.include_tasks: tasks/cleanup.yml
