---
- name: Set up macOS for actual work
  hosts: all
  vars_files:
    - packages.yml
    - dotfiles.yml
  tasks:
    - ansible.builtin.include_tasks: tasks/dotfiles.yml
    - ansible.builtin.include_tasks:
        file: tasks/software.yml
        apply:
          become_flags: -A
          environment:
            SUDO_ASKPASS: "{{ ansible_env.HOME }}/bin/op-sudo"
    - ansible.builtin.include_tasks: tasks/cleanup.yml
