---
- name: Install Package Managers
  hosts: all
  vars_files:
    - packages.yml
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas


- name: Remove Ansible Bootstrap Installation
  hosts: all
  vars:
    ansible_bs: "{{ ansible_env.ANSIBLE_BS | default(ansible_user_home + '/.ansible-bootstrap') }}"
  tasks:
    - name: Directory is absent - {{ ansible_bs }}
      ansible.builtin.file:
        path: "{{ ansible_bs }}"
        state: absent
