---
- hosts: all
  name: Log in to the Mac App Store
  vars_files:
    - "{{ ansible_env.HOME }}/.mas-credentials.yml"
  tasks:
    - name:
      script: mas_login.scpt
      environment:
        MAS_LOGIN: "{{ mas_login }}"
        MAS_PASSWORD: "{{ mas_password }}"

- hosts: all
  name: Install Package Managers
  roles:
    - geerlingguy.homebrew
    - geerlingguy.mas

- hosts: all
  name: Pivot Ansible Installation to Homebrew
  tasks:

    - name: Check for bootstrap installation of Ansible
      stat:
        path: "{{ ansible_env.HOME }}/.ansible-bootstrap"
      register: ansible_bootstrap

    - name: Install Ansible with Homebrew
      homebrew:
        name: ansible
        state: latest
      register: ansible_brew_install
      when: ansible_bootstrap.stat.exists and ansible_bootstrap.stat.isdir

    - name: Remove Ansible Bootstrap Installation
      file:
        path: "{{ ansible_env.HOME }}/.ansible-bootstrap"
        state: absent
      when: not ansible_brew_install is failed
