---
- hosts: all

  roles:
    - workstation-icloud
    - workstation-office
    - workstation-photography
    - workstation-vagrant
    - defaults-software
    - macOS-defaults

- hosts: all
  name: Pivot Ansible Installation to Homebrew
  tasks:

    - name: Install Ansible with Homebrew
      homebrew:
        name: ansible
        state: latest
      register: ansibrew

    - name: Remove Ansible Bootstrap Installation
      file:
        path: "{{ ansible_env.HOME }}/.ansible-bootstrap"
        state: absent
      when: not ansibrew.failed
