---
- name: Install Homebrew If Necessary
  shell: >
    /usr/bin/yes
    | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
  args:
    creates: /usr/local/bin/brew

- name: Tap Homebrew Cask
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: Install Homebrew Cask Packages
  homebrew_cask:
    state: present
    name: "{{ item }}"
  loop: "{{ homebrew_cask_apps }}"

- name: Install Packages
  homebrew:
    state: present
    name: "{{ item }}"
  loop: "{{ homebrew_installed_packages }}"

