---
- name: Change macOS dock preferences
  hosts: all
  tasks:
    - name: Rearrange Desktop Spaces Based on Use
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: "{{ dock_mru_spaces }}"
      when:
        - dock_mru_spaces is defined
        - dock_mru_spaces is not none
      notify: restart Dock
    
    - name: Which screen edge for the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: orientation
        type: string
        value: "{{ dock_orientation }}"
      when:
        - dock_orientation is defined
        - dock_orientation is not none
      notify: restart Dock
    
    - name: Automatically Hide and Show the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: "{{ dock_autohide }}"
      when:
        - dock_autohide is defined
        - dock_autohide is not none
      notify: restart Dock
    
    - name: Remove Dock Autohide Delay
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        type: float
        value: "{{ dock_autohide_delay }}"
      when:
        - dock_autohide_delay is defined
        - dock_autohide_delay is not none
      notify: restart Dock
    
    - name: Only Show Running Apps in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: static-only
        type: bool
        value: "{{ dock_active_only }}"
      when:
        - dock_active_only is defined
        - dock_active_only is not none
      notify: restart Dock
    
    - name: Single App Mode
      community.general.osx_defaults:
        domain: com.apple.dock
        key: single-app
        type: bool
        value: "{{ dock_single_app }}"
      when:
        - dock_single_app is defined
        - dock_single_app is not none
      notify: restart Dock
    
    - name: Dock Minimization Effect
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mineffect
        type: bool
        value: "{{ dock_mineffect }}"
      when:
        - dock_mineffect is defined
        - dock_mineffect is not none
      notify: restart Dock
    
    - name: Dock Magnification Effect
      community.general.osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: "{{ dock_magnify }}"
      when:
        - dock_magnify is defined
        - dock_magnify is not none
      notify: restart Dock

  handlers:
    - name: restart Dock
      ansible.builtin.command:
        cmd: killall Dock
