---
- name: Install dotfiles into user account
  hosts: all
  vars:
    dotfiles_repo: >-
      {{ ansible_env.DOTFILES_REPO
         | default("https://github.com/stephenulmer/dotfiles.git") }}
    dotfiles_gitdir: >-
      {{ ansible_env.DOTFILES_GITDIR
         | ansible_env.HOME ~ "/.dotfiles" }}

  tasks:
    - name: dotfiles repository has local clone
      ansible.builtin.git:
        repo: "git@github.com:stephenulmer/dotfiles"
        accept_newhostkey: true
        dest: "{{ dotfiles_gitdir }}"
        bare: true
        update: false
    
    - name: working tree is checked-out
      ansible.builtin.command:
        cmd: git checkout main .
        chdir: "{{ ansible_env.HOME }}"
      changed_when: "'Updated 0 paths' not in git_checkout.stderr"
      environment:
        GIT_DIR: "{{ dotfiles_gitdir }}"
        GIT_WORK_TREE: "{{ ansible_env.HOME }}"
      register: git_checkout
    
    - name: dotfiles repo has core.bare false
      community.general.git_config:
        repo: "{{ dotfiles_gitdir }}"
        scope: local
        name: core.bare
        value: "false"
    
    - name: dotfiles repo has status.showUntrackedFiles no
      community.general.git_config:
        repo: "{{ dotfiles_gitdir }}"
        scope: local
        name: status.showUntrackedFiles
        value: "no"
    
    - name: emacs packages are installed
      ansible.builtin.command:
        cmd: emacs -nw --batch --user= --load=init.el
        chdir: "{{ ansible_env.HOME }}/.emacs.d"
      changed_when: emacs_init.stderr_lines | length > 0
      ignore_errors: true
      register: emacs_init
