---
- name: Install Analytics Software
  hosts: all
  vars:
    homebrew_cask_apps:
      - aquamacs
      - xquartz

    homebrew_installed_packages:
      - pyenv
      - pyenv-virtualenv
      - graphviz
      - r

  roles:
    - geerlingguy.homebrew
