---
- name: Configure trackpad
  hosts: all
  pre_tasks:
    - name: Probe full disk access for macOS Terminal
      ansible.builtin.stat:
        path: /Library/Preferences/com.apple.TimeMachine.plist
      register: stat_probe

    - name: Fail if Terminal can't read restricted file
      ansible.builtin.fail:
        msg: |
          Terminal does not have Full Disk Access!

          Add Terminal to the Full Disk Access list in
          System Preferences > Security & Privacy. Then
          restart the terminal and re-run this playbook.
      when: stat_probe.stat.mimetype == 'unknown'

  tasks:
    - name: Enable screen zoom with ctrl and scroll gesture
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: closeViewScrollWheelToggle
        type: bool
        value: "{{ trackpad_zoom }}"
      when:
        - trackpad_zoom is defined
        - trackpad_zoom is not none

    - name: Enable screen zoom with ctrl and scroll gesture (part deux)
      community.general.osx_defaults:
        domain: com.apple.universalaccess
        key: HIDScrollZoomModifierMask
        type: int
        value: 262144
      when:
        - trackpad_zoom is defined
        - trackpad_zoom is not none

    - name: Enable three finger drag gesture (standard driver)
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadThreeFingerDrag
        type: int
        value: "{{ trackpad_3finger_drag | bool | ternary('1', '0') }}"
      when:
        - trackpad_3finger_drag is defined
        - trackpad_3finger_drag is not none

    - name: Enable three finger drag gesture (bluetooth driver)
      community.general.osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        key: TrackpadThreeFingerDrag
        type: int
        value: "{{ trackpad_3finger_drag | bool | ternary('1', '0') }}"
      when:
        - trackpad_3finger_drag is defined
        - trackpad_3finger_drag is not none

    - name: Enable tap to click (standard driver)
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: "{{ trackpad_tap_to_click | bool | ternary('1', '0') }}"
      when:
        - trackpad_tap_to_click is defined
        - trackpad_tap_to_click is not none

    - name: Enable tap to click (bluetooth driver)
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: "{{ trackpad_tap_to_click | bool | ternary('1', '0') }}"
      when:
        - trackpad_tap_to_click is defined
        - trackpad_tap_to_click is not none
